DROP TABLE IF EXISTS SUBSCRIPTION;
CREATE TABLE SUBSCRIPTION( ID INT AUTO_INCREMENT PRIMARY KEY, SUBSCRIPTION_NAME VARCHAR(250) NOT NULL, MONTHLY_PRICE VARCHAR(250) NOT NULL, LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO SUBSCRIPTION (SUBSCRIPTION_NAME, MONTHLY_PRICE,LAST_UPDATE) VALUES
  ('VIDEO_SUB_1', '27',CURRENT_TIMESTAMP),
  ('VIDEO_SUB_2', '87',CURRENT_TIMESTAMP),
  ('VIDEO_SUB_3', '55',CURRENT_TIMESTAMP);